### ISSUE TITLE
add avni connector to platform

### ISSUE THREAD

**Issue by fatchat** [DevDataPlatform/DDP_backend#232]
add the avni configuration to `setup_airbyte_workspace` in `airbytehelpers.py`

**Comment by fatchat** [comment]
create single `production` branch from `Staging` branch in our airbyte fork
merge into this `production` branch:
- `feature/source-avni`
- `feature/update_commcare`
- `feature/commcareCheckConnection`
- `feature/source_kobo_tool`

**Comment by fatchat** [comment]
avni's `spec.yaml` is missing the `title` for the propertiesfields i.e under the `description`s 

e.g.
```
  properties:
    username:
      type: string
      description: Your avni platform Username
      title: Your avni platform Username
```
etc.
